---
version: '3.7'
services:

  # ddclient - keep ddns updated
  ddclient:
    image: linuxserver/ddclient
    init: true
    hostname: ddclient
    container_name: ddclient
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/docker/ddclient:/config
      - shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - utilities

  # duplicati - store backups online with strong encryption
  duplicati:
    image: linuxserver/duplicati
    init: true
    hostname: duplicati
    container_name: duplicati
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/docker/duplicati:/config
      - ${DOCKERDIR}/docker/backups:/backups
      - ${DOCKERDIR}/docker:/source
      - shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik
    labels:
      - "traefik.http.routers.backup.rule=Host(`backup.${HOSTNAME}`)"
      - "traefik.http.routers.backup.tls=true"
      - "traefik.http.routers.backup.tls.certresolver=le"
      - "traefik.http.routers.backup.entrypoints=websecure"
      - "traefik.http.services.backup.loadbalancer.server.port=8200"

  # Heimdall - Application dashboard
  heimdall:
    image: linuxserver/heimdall
    init: true
    hostname: heimdall
    container_name: heimdall
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/docker/heimdall:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.${HOSTNAME}`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=le"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.services.dashboard.loadbalancer.server.port=80"

  # Portainer - WebUI for Containers
  portainer:
    image: portainer/portainer
    init: true
    hostname: portainer
    container_name: portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERDIR}/docker/portainer/data:/data
      - shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik
    labels:
      - "traefik.http.routers.portainer.rule=Host(`portainer.${HOSTNAME}`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=le"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  # Traefik v2 - reverse proxy for containers
  traefik:
    image: traefik:latest
    init: true
    hostname: traefik
    container_name: traefik
    restart: unless-stopped
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.file.filename=/etc/traefik/files.yml
      - --providers.file.watch=true
      - --api.dashboard=true
      - --certificatesresolvers.le.acme.email=${EMAIL}
      - --certificatesresolvers.le.acme.storage=/etc/traefik/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --log.level=DEBUG
      - --log.filePath=/etc/traefik/traefik.log
      - --serversTransport.insecureSkipVerify=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/etc/traefik
      - shared:/shared
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.${HOSTNAME}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.middlewares.auth.basicauth.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"

  # Watchtower - docker image updater
  watchtower:
    image: containrrr/watchtower
    init: true
    hostname: watchtower
    container_name: watchtower
    restart: unless-stopped
    command: --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERDIR}/docker/watchtower/data:/data
      - shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - utilities

networks:
  traefik:
    name: traefik
    ipam:
      config:
        - subnet: 172.18.0.0/16
  utilities:
    name: utilities
    ipam:
      config:
        - subnet: 172.19.0.0/16

volumes:
  letsencrypt:
  shared:
    name: shared
