version: "3.7"
services:

#Portainer - WebUI for Containers
  portainer:
    image: portainer/portainer
    hostname: portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}

# Organizer - Unified HTPC/Home Server Web Interface
  organizr:
    container_name: organizr
    hostname: organizr
    restart: always
    image: linuxserver/organizr:latest
    volumes:
      - ${USERDIR}/docker/organizr:/config
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "80:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# Watchtower - Automatic Update of Containers/Apps
  watchtower:
    container_name: watchtower
    hostname: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup

# Sonarr – TV Show Download and Management
  sonarr:
    image: linuxserver/sonarr:preview
    hostname: sonarr
    container_name: sonarr
    volumes:
      - ${USERDIR}/docker/sonarr:/config
      - ${DATADIR}/downloads:/downloads
      - ${DATADIR}/complete:/downloads/complete
      - ${DATADIR}/My TV:/tv
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "8989:8989"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# Radarr – Movie Download and Management
  radarr:
    image: linuxserver/radarr:latest
    hostname: radarr
    container_name: radarr
    volumes:
      - ${USERDIR}/docker/radarr:/config
      - ${DATADIR}/downloads:/downloads
      - ${DATADIR}/complete:/downloads/complete
      - ${DATADIR}/My Videos:/movies
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "7878:7878"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# Lidarr – TV Show Download and Management
  lidarr:
    image: hotio/lidarr
    hostname: lidarr
    container_name: lidarr
    volumes:
      - ${USERDIR}/docker/lidarr:/config
      - ${DATADIR}/downloads:/downloads
      - ${DATADIR}/complete:/downloads/complete
      - ${DATADIR}/My Music:/music
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "8686:8686"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# NZBHydra2 - Indexer 
  nzbhydra2:
    image: hotio/nzbhydra2:latest
    hostname: nzbhydra
    container_name: nzbhydra
    volumes:
      - ${USERDIR}/docker/nzbhydra:/config
      - ${DATADIR}/downloads:/downloads
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "5076:5076"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# NZBGet - Downloader      
  nzbget:
    image: linuxserver/nzbget:latest
    hostname: nzbget
    container_name: nzbget
    volumes: 
      - ${USERDIR}/docker/nzbget:/config
      - ${DATADIR}/downloads:/downloads
      - ${DATADIR}/complete:/downloads/complete
      - ${DATADIR}/incomplete:/downloads/incomplete
      - ${DATADIR}/queue:/downloads/queue
      - ${DATADIR}/temp:/downloads/temp
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "6789:6789"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# Ombi - Show Requestor      
  ombi:
    image: linuxserver/ombi:latest
    hostname: ombi
    container_name: ombi
    volumes: 
      - ${USERDIR}/docker/ombi:/config
    ports:
      - "3579:3579"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
