---
version: '3.7'
services:

  # NZBHydra2 - Meta search for NZB News Indexers
  nzbhydra2:
    image: linuxserver/hydra2:latest
    hostname: nzbhydra
    container_name: nzbhydra
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/docker/nzbhydra:/config
      - ${DOCKERDIR}/downloads:/downloads
      - shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik
    labels:
      - "traefik.http.routers.nzbhydra.rule=Host(`nzbhydra.${HOSTNAME}`)"
      - "traefik.http.routers.nzbhydra.tls=true"
      - "traefik.http.routers.nzbhydra.tls.certresolver=le"
      - "traefik.http.routers.nzbhydra.entrypoints=websecure"
      - "traefik.http.services.nzbhydra.loadbalancer.server.port=5076"

  # Ombi - Show Requestor
  ombi:
    image: linuxserver/ombi:latest
    hostname: ombi
    container_name: ombi
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/docker/ombi:/config
      - shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik
    labels:
      - "traefik.http.routers.ombi.rule=Host(`ombi.${HOSTNAME}`)"
      - "traefik.http.routers.ombi.tls=true"
      - "traefik.http.routers.ombi.tls.certresolver=le"
      - "traefik.http.routers.ombi.entrypoints=websecure"
      - "traefik.http.services.ombi.loadbalancer.server.port=3579"

  # Radarr – Movie Download and Management
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/docker/radarr:/config
      - ${DOCKERDIR}/downloads:/downloads
      - ${DATADIR}/My Videos:/movies
      - shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik
    labels:
      - "traefik.http.routers.radarr.rule=Host(`radarr.${HOSTNAME}`)"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=le"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  # SABnzbd - Binary News Reader
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    hostname: sabnzbd
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/docker/sabnzbd:/config
      - ${DOCKERDIR}/downloads:/downloads
      - shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik
    labels:
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${HOSTNAME}`)"
      - "traefik.http.routers.sabnzbd.tls=true"
      - "traefik.http.routers.sabnzbd.tls.certresolver=le"
      - "traefik.http.routers.sabnzbd.entrypoints=websecure"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"

  # Sonarr – TV Show Download and Management
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/docker/sonarr:/config
      - ${DOCKERDIR}/downloads:/downloads
      - ${DATADIR}/My TV:/tv
      - shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik
    labels:
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${HOSTNAME}`)"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=le"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

networks:
  traefik:
    external:
      name: traefik

volumes:
  shared:
    external: true
