---
version: '3.7'
services:

  # ddclient - keep ddns updated
  ddclient:
    image: linuxserver/ddclient
    init: true
    hostname: ddclient
    container_name: ddclient
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/docker/ddclient:/config
      - shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  # duplicati - store backups online with strong encryption
  duplicati:
    image: linuxserver/duplicati
    init: true
    hostname: duplicati
    container_name: duplicati
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/docker/duplicati:/config
      - ${DOCKERDIR}/docker/backups:/backups
      - ${DOCKERDIR}/docker:/source
      - shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=backup"
      - "traefik.frontend.rule=Host:backup.${HOSTNAME}"
      - "traefik.port=8200"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${HOSTNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=false"

  # Heimdall - Application dashboard
  heimdall:
    image: linuxserver/heimdall
    init: true
    hostname: heimdall
    container_name: heimdall
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/docker/heimdall:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=dashboard"
      - "traefik.frontend.rule=Host:dashboard.${HOSTNAME}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${HOSTNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

  # PiHole - network ad blocker
  pihole:
    image: pihole/pihole:latest
    init: true
    hostname: pihole
    container_name: pihole
    domainname: docker
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/docker/pihole:/etc/pihole
      - ${DOCKERDIR}/docker/pihole/pihole.log:/var/log/pihole.log
      - ${DOCKERDIR}/docker/pihole/dnsmasq.d:/etc/dnsmasq.d
    environment:
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=pihole.${HOSTNAME}
      - VIRTUAL_PORT=80
      - TZ=${TZ}
      - WEBPASSWORD=${HTTP_PASSWORD}
      - DNS1=127.0.0.1
      - DNS2=1.1.1.1
    networks:
      - traefik
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '8043:80/tcp'
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=HostRegexp:pihole.${HOSTNAME},{catchall:.*}"
      - "traefik.frontend.priority=1"
      - "traefik.backend=pihole"
      - "traefik.port=80"

  # Portainer - WebUI for Containers
  portainer:
    image: portainer/portainer
    init: true
    hostname: portainer
    container_name: portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERDIR}/docker/portainer/data:/data
      - shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.${HOSTNAME}"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${HOSTNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=false"

  # Traefik - reverse proxy for containers
  traefik:
    image: traefik:v1.7.20-alpine
    init: true
    hostname: traefik
    container_name: traefik
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/etc/traefik
      - shared:/shared
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${HOSTNAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${HOSTNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=false"
      - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"

  # Watchtower - docker image updater
  watchtower:
    image: containrrr/watchtower
    init: true
    hostname: watchtower
    container_name: watchtower
    restart: unless-stopped
    command: --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERDIR}/docker/watchtower/data:/data
      - shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

networks:
  traefik:
    external:
      name: traefik

volumes:
  letsencrypt:
  shared:
    external: true
